export const ADD_INFO = 'ADD_INFO';
export const ADD_EDUCATION = 'ADD_EDUCATION';
export const ADD_WORK = 'ADD_WORK';
export const ADD_APTITUDE = 'ADD_APTITUDE';
export const ADD_RECOMMENDATION = 'ADD_RECOMMENDATION';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const DELETE_APTITUDE = 'DELETE_APTITUDE';